// Local Imports
import { ChannelCreateHandler as ChannelCreateHandlerClass } from './channel-create-handler';
import { ChannelDeleteHandler as ChannelDeleteHandlerClass } from './channel-delete-handler';
import { ChannelUpdateHandler as ChannelUpdateHandlerClass } from './channel-update-handler';
import { EmojiCreateHandler as EmojiCreateHandlerClass } from './emoji-create-handler';
import { EmojiDeleteHandler as EmojiDeleteHandlerClass } from './emoji-delete-handler';
import { EmojiUpdateHandler as EmojiUpdateHandlerClass } from './emoji-update-handler';
import { ErrorHandler as ErrorHandlerClass } from './error-handler';
import { GuildBanAddHandler as GuildBanAddHandlerClass } from './guild-ban-add-handler';
import { GuildBanRemoveHandler as GuildBanRemoveHandlerClass } from './guild-ban-remove-handler';
import { GuildCreateHandler as GuildCreateHandlerClass } from './guild-create-handler';
import { GuildDeleteHandler as GuildDeleteHandlerClass } from './guild-delete-handler';
import { GuildMemberAddHandler as GuildMemberAddHandlerClass } from './guild-member-add-handler';
import { GuildMemberRemoveHandler as GuildMemberRemoveHandlerClass } from './guild-member-remove-handler';
import { GuildMemberUpdateHandler as GuildMemberUpdateHandlerClass } from './guild-member-update-handler';
import { GuildScheduledEventCreateHandler as GuildScheduledEventCreateHandlerClass } from './guild-scheduled-event-create-handler';
import { GuildScheduledEventDeleteHandler as GuildScheduledEventDeleteHandlerClass } from './guild-scheduled-event-delete-handler';
import { GuildScheduledEventUpdateHandler as GuildScheduledEventUpdateHandlerClass } from './guild-scheduled-event-update-handler';
import { GuildScheduledEventUserAddHandler as GuildScheduledEventUserAddHandlerClass } from './guild-scheduled-event-user-add-handler';
import { GuildScheduledEventUserRemoveHandler as GuildScheduledEventUserRemoveHandlerClass } from './guild-scheduled-event-user-remove-handler';
import { GuildUpdateHandler as GuildUpdateHandlerClass } from './guild-update-handler';
import { InteractionCreateHandler as InteractionCreateHandlerClass } from './interaction-create-handler';
import { MessageCreateHandler as MessageCreateHandlerClass } from './message-create-handler';
import { MessageDeleteHandler as MessageDeleteHandlerClass } from './message-delete-handler';
import { MessageReactionAddHandler as MessageReactionAddHandlerClass } from './message-reaction-add-handler';
import { MessageReactionRemoveHandler as MessageReactionRemoveHandlerClass } from './message-reaction-remove-handler';
import { RateLimitHandler as RateLimitHandlerClass } from './rate-limit-handler';
import { ReadyHandler as ReadyHandlerClass } from './ready-handler';
import { RoleCreateHandler as RoleCreateHandlerClass } from './role-create-handler';
import { RoleDeleteHandler as RoleDeleteHandlerClass } from './role-delete-handler';
import { RoleUpdateHandler as RoleUpdateHandlerClass } from './role-update-handler';
import { UserUpdateHandler as UserUpdateHandlerClass } from './user-update-handler';

export const ChannelCreateHandler = new ChannelCreateHandlerClass();
export const ChannelDeleteHandler = new ChannelDeleteHandlerClass();
export const ChannelUpdateHandler = new ChannelUpdateHandlerClass();
export const EmojiCreateHandler = new EmojiCreateHandlerClass();
export const EmojiDeleteHandler = new EmojiDeleteHandlerClass();
export const EmojiUpdateHandler = new EmojiUpdateHandlerClass();
export const ErrorHandler = new ErrorHandlerClass();
export const GuildBanAddHandler = new GuildBanAddHandlerClass();
export const GuildBanRemoveHandler = new GuildBanRemoveHandlerClass();
export const GuildCreateHandler = new GuildCreateHandlerClass();
export const GuildDeleteHandler = new GuildDeleteHandlerClass();
export const GuildMemberAddHandler = new GuildMemberAddHandlerClass();
export const GuildMemberRemoveHandler = new GuildMemberRemoveHandlerClass();
export const GuildMemberUpdateHandler = new GuildMemberUpdateHandlerClass();
export const GuildScheduledEventCreateHandler = new GuildScheduledEventCreateHandlerClass();
export const GuildScheduledEventDeleteHandler = new GuildScheduledEventDeleteHandlerClass();
export const GuildScheduledEventUpdateHandler = new GuildScheduledEventUpdateHandlerClass();
export const GuildScheduledEventUserAddHandler = new GuildScheduledEventUserAddHandlerClass();
export const GuildScheduledEventUserRemoveHandler = new GuildScheduledEventUserRemoveHandlerClass();
export const GuildUpdateHandler = new GuildUpdateHandlerClass();
export const InteractionCreateHandler = new InteractionCreateHandlerClass();
export const MessageCreateHandler = new MessageCreateHandlerClass();
export const MessageDeleteHandler = new MessageDeleteHandlerClass();
export const MessageReactionAddHandler = new MessageReactionAddHandlerClass();
export const MessageReactionRemoveHandler = new MessageReactionRemoveHandlerClass();
export const RateLimitHandler = new RateLimitHandlerClass();
export const ReadyHandler = new ReadyHandlerClass();
export const RoleCreateHandler = new RoleCreateHandlerClass();
export const RoleDeleteHandler = new RoleDeleteHandlerClass();
export const RoleUpdateHandler = new RoleUpdateHandlerClass();
export const UserUpdateHandler = new UserUpdateHandlerClass();
